version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: govconn-backend-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${SUPABASE_DB_URL}
    volumes:
      - ./backend:/app

  ai_assistant:
    build:
      context: ./ai-assistant
      dockerfile: Dockerfile
    container_name: gov_ai_assistant
    restart: always
    ports:
      - "8100:8000" # container 8000 -> host 8100
    environment:
      - BACKEND_URL=http://backend:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - backend
      - redis
    volumes:
      - ./ai-assistant:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: govconn-frontend-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_AI_URL=http://ai_assistant:8000
    depends_on:
      - backend
      - ai_assistant

  GovPortal:
    build:
      context: ./GovPortal
      dockerfile: Dockerfile
    container_name: gov_frontend_admin
    restart: always
    ports:
      - "3001:4173"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_AI_URL=http://ai_assistant:8000
    depends_on:
      - backend
      - ai_assistant

  redis:
    image: redis:7-alpine
    container_name: gov_redis
    restart: always
    ports:
      - "6379:6379"
